### ISSUE TITLE
No way to call acquireTokenPopup or acquireTokenRedirect?

### ISSUE THREAD

**Issue by mammons** [frankchen76/EZCode-Adal-Angular5#2]
Is there a way to handle the situation where, when trying to acquire a token we get back an "interaction_required" error? The Power BI api is requiring multi-factor authentication, but I have no way to handle conditional access.

**Comment by frankchen76** [comment]
@mammons when you add ezcode-adal-angular5 to your spa application, did your applicatin redirect to AAD login page? Based on my understanding about MFA, if you enable AAD MFA, it should be part of your AAD login process. Once you are able to login, the AAD will redirect to your SPA application with access token which you can use for your Power BI REST endpoint. At same time, did you enable implicit flow by add `"oauth2AllowImplicitFlow": true` in your AAD manifest setting?

**Comment by mammons** [comment]
It redirects to the login fine and I'm passing the endpoints I'd also like to get permissions to. So I get my AD access token, but it also sends back an interaction_required ADAL error for the Power BI token because of the multi-factor. According to [this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-conditional-access-developer ) the proper flow is to catch that and use one of the other acquireToken methods to redirect to the MFA page to authenticate that way. I was able to sort of hack it in to use the acquireTokenRedirect function, but then the handleWindowCallback function was erroring out. I ended up just using MSAL.js but you may be able to check for an adal.error in acquireToken and then use one of the other methods.

**Comment by frankchen76** [comment]
@mammons sorry to get back to you late. I updated my code to include a acquireTokenPopup or acquireTokenRedirect methods in EZCodeAdalService. Feel free to try MFA authentication flow from your end. Please check the latest one from [ezcode-adal-angular5(1.0.9)@npm](https://www.npmjs.com/package/ezcode-adal-angular5) and [EZCode-Adal-Angular5 Github](https://github.com/frankchen76/EZCode-Adal-Angular5). Post your questions if you have. Thanks again for using this library.

**Comment by mammons** [comment]
Thank you!
