### ISSUE TITLE
When getAccessTokenByUrl method is called getting error in console Cannot match any routes. URL Segment: 'access_token'

### ISSUE THREAD

**Issue by saikarthikj** [frankchen76/EZCode-Adal-Angular5#6]
When getAccessTokenByUrl  method is invoked to get token for different endpoint, I am getting the token but with an error in the console saying- "Cannot match any routes. URL Segment: 'access_token'".
Angular is trying to match component for for **access_token** route. Please suggest how to reslove this issue.

**Comment by frankchen76** [comment]
@saikarthikj sorry for late response. When you check ezcode-adal-module.ts, you will find out I defined a route for access_token callback at line 18. Can you please verify?

- if you are using Angular 5? someone report there is an error for Angular 6. I am still working on that. 
- if you added useHash:true in your Route configuration at app.module.ts like below: 
```
@NgModule({
    declarations: [
    ....
    ],
    imports: [
        ....
        RouterModule.forRoot(rootRouterConfig, { useHash: true })
    ],
    providers: [
     .....
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by saikarthikj** [comment]
Thanks access_token callback worked.
