### ISSUE TITLE
Http Intercept Set token issue with Power BI RestAPI

### ISSUE THREAD

**Issue by saikarthikj** [frankchen76/EZCode-Adal-Angular5#7]
Http Intercept set Authorization by concat of  'bearer' + token so Power-Bi RestAPI return with 403 because   letter 'b' is small case 'bearer'. If letter 'b'  is upper case('Bearer' + token) it's work fine.

Please update in later version to upper case.

**Comment by frankchen76** [comment]
@saikarthikj thanks for your input. the lib was updated to [1.0.10](https://www.npmjs.com/package/ezcode-adal-angular5) for the fix.
